version: '3.1'

services:
  www:
    container_name: gravtest_www
    image: outrigger/apache-php:php70
    network_mode: "bridge"
    environment:
      DOCROOT: /var/www
    volumes:
      - .:/var/www/
    labels:
      com.dnsdock.name: www
      com.dnsdock.image: gravtest
      outrigger.project: gravtest
